Deeper and Darker Compat
SigmundGranaas/forgero pull request #949
Opened 2024-07-18 09:06 UTC by JorisDeBeer

:)

2024-07-18 19:09 UTC, SigmundGranaas requested changes
Looks good! Echo planks needs to be changed to just echo for the recipe system to not throw a fit. :+1:

2024-07-18 20:03 UTC, SigmundGranaas approved these changes
Works well as long as #952 get merged. Good job!

2024-07-18 20:10 UTC, SigmundGranaas commented
Wait, we should add deeper_and_darker to the list of compatible mods in the fabric.mod.json file: https://github.com/SigmundGranaas/forgero/blob/f8a5b5bd13d0feb036a1b1ef7988722946bc893b/fabric/build.gradle#L112-L122

2024-07-18 22:55 UTC, JorisDeBeer commented
Could you invite me to the modrinth page too? 

Then I can add the new compats to the mod description page too

2024-07-19 05:22 UTC, SigmundGranaas commented
You have been invited

2024-07-19 08:26 UTC, JorisDeBeer commented
bro gave me zero permission to do anything lol 

Cant edit the description

2024-07-19 08:28 UTC, SigmundGranaas commented
Redact this inaccurate statement

2024-07-19 08:29 UTC, JorisDeBeer commented
I AM SORRY SIR

2024-07-26 09:59 UTC, SigmundGranaas requested changes
Small merge fix needs to be applied with the blaze rod fix, also the mod needs to be added to modrinth suggestions as well. Other than that, looks good to go!

2024-07-26 09:59 UTC, SigmundGranaas commented on fabric/build.gradle
> +				optionalDependency "deeperdarker"
Add this to the modrinth list as well.

2024-07-26 11:03 UTC, SigmundGranaas approved these changes
Looks good!

2024-07-27 07:48 UTC, merged